### ISSUE TITLE
All SDK 2013 Multiplayer Projects Crash Upon Map Load

### ISSUE THREAD

**Issue by Gocnak** [ValveSoftware/source-sdk-2013#424] opened 2017-06-17 01:05 UTC
Ever since [the update on June 15th regarding Steam audio and engine fixes](http://store.steampowered.com/news/30120/), any game that uses SDK 2013 Multiplayer crashes upon loading a map. SDK 2013 Singleplayer is unaffected, probably due to being on a more stable branch.

To re-create this (in the base SDK 2013 Multiplayer game no less):
1. Start up SDK 2013 Multiplayer from tools
2. Click "Video Stress Test" (or go into any map)
3. Crash and burn
4. Cry as you realize that your game built on the same engine is also affected

Tested the above on Windows 10 64bit, and I have reports from team members that Linux (Debian) seems to be worse; the game doesn't even get to the menu before ~crashing~ failing to load `engine.so` and aborting.

If this isn't the right place to report these kinds of things, please let me know.

Thanks!

**Comment by Nephyrin** [comment] 2017-06-17 01:23
It appears this only affects launching the engine in single-player mode.  A fix is on the way.

In the meantime, a workaround is to run with `maxplayers 2`.

**Comment by Nephyrin** [comment] 2017-06-19 21:08
We've just shipped a client update that should fix this:
http://store.steampowered.com/news/30173/

**Comment by tempacc123** [comment] 2017-06-19 21:20
oh wow. thanks!

**Comment by darealshinji** [comment] 2017-06-23 12:33
Can you update the Github repository so that it includes the recent bugfixes?

**Comment by darealshinji** [comment] 2017-07-11 07:07
Not sure why people reacted with a confused emoji on my previous question. Last code update on this repository was from 2015, so it doesn't include all the recent changes and bugfixes.

**Comment by neico** [comment] 2017-07-11 07:46
This specific issue wasn't caused by something present in this code repo as it's most likely somewhere inside the engine, so there's nothing to update here.

Anything beyond that is a general concern which is off-topic and covered in various other places.

**Comment by kisak-valve** [comment] 2017-07-11 12:34
Closing per the [2017-06-19 Source SDK 2013](http://store.steampowered.com/news/30173/) update and the last comment.

**Closed by kisak-valve** 2017-07-11 12:34 UTC
Labels: Reviewed

**Comment by strubium** [comment] 2023-10-20 01:22
Still having this issue in 2023.
