### ISSUE TITLE
Include gamui in the SDK

### ISSUE THREAD

**Issue by n0p3** [ValveSoftware/source-sdk-2013#409] opened 2017-02-28 10:39 UTC
It would be greatly appreciated if you could consider providing the gameui source like in the ASW SDK. Having everybody rebuild the dialogs with the ASW Source (and add missing features etc) does not seem very straight forward ..

**Comment by kisak-valve** [comment] 2017-02-28 15:49
Closing as a duplicate of #370.

**Closed by kisak-valve** 2017-02-28 15:49 UTC
