### ISSUE TITLE
Broken Cubemaps in 2013 SP Branch

### ISSUE THREAD

**Issue by GamerDude27** [ValveSoftware/source-sdk-2013#398] opened 2016-11-17 09:15 UTC
Hello,

Building cubemaps in Source 2013 is STILL broken, and has been for the longest of time. To my knowledge it was fixed for multiplayer some time ago. Any chance we can get a fix for the SP branch as well? Having to work around this is not very pleasant if you ask me.

"An updated vbsp with lightmaps on static props would be awesome as well, and something mods could really benefit from." - joeangry, issue #389

At: @Nephyrin @alfred-valve @JoeLudwig

Thank you

**Comment by Nephyrin** [comment] 2016-12-13 02:11
Duplicate of #389

**Closed by Nephyrin** 2016-12-13 02:11 UTC
